#!/usr/bin/env bash

set -euo pipefail

KUBECONFIG_PATH="${KUBECONFIG:-$HOME/.kube/dena-config}"
export KUBECONFIG="$KUBECONFIG_PATH"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOCAL_DIR="$REPO_ROOT/.local"
LOCAL_ENV="$LOCAL_DIR/fase12-keycloak.env"
OUT_DIR="$LOCAL_DIR/recovery"
REALM="${DENA_RECOVERY_REALM:-piloto}"
USERNAME="${DENA_RECOVERY_USERNAME:-adminuser}"
ISSUED_BY="${DENA_RECOVERY_ISSUED_BY:-recovery-operator}"
COUNT="${DENA_RECOVERY_CODES_COUNT:-10}"

for bin in kubectl openssl sha256sum; do
  command -v "$bin" >/dev/null 2>&1 || {
    echo "Falta binario requerido: $bin" >&2
    exit 1
  }
done

mkdir -p "$LOCAL_DIR" "$OUT_DIR"
chmod 700 "$OUT_DIR"

kubectl rollout status statefulset/postgresql-datalake -n datalake --timeout=180s >/dev/null
pg_password="$(kubectl get secret -n datalake postgresql-datalake -o jsonpath='{.data.postgres-password}' | base64 -d)"

kubectl exec -i -n datalake postgresql-datalake-0 -- \
  env PGPASSWORD="$pg_password" \
  psql -v ON_ERROR_STOP=1 -U postgres -d datalake <"$REPO_ROOT/sql/04-dena-recovery.sql"

if [[ -r "$LOCAL_ENV" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "$LOCAL_ENV"
  set +a
fi

codes_file="$OUT_DIR/${REALM}-${USERNAME}-backup-codes.txt"
: >"$codes_file"
tmp_sql="$(mktemp /tmp/dena-recovery-codes.XXXXXX.sql)"
trap 'rm -f "$tmp_sql"' EXIT

{
  echo "BEGIN;"
  for _ in $(seq 1 "$COUNT"); do
    code="$(openssl rand -hex 2 | tr '[:lower:]' '[:upper:]')-$(openssl rand -hex 2 | tr '[:lower:]' '[:upper:]')-$(openssl rand -hex 2 | tr '[:lower:]' '[:upper:]')-$(openssl rand -hex 2 | tr '[:lower:]' '[:upper:]')"
    code_hash="$(printf '%s' "$code" | sha256sum | awk '{print $1}')"
    code_hint="${code:0:4}"
    printf '%s\n' "$code" >>"$codes_file"
    cat <<SQL
INSERT INTO dena.recovery_backup_code (
  realm, username, code_hash, code_hint, status, issued_by, notes
) VALUES (
  '$REALM',
  '$USERNAME',
  '$code_hash',
  '$code_hint',
  'issued',
  '$ISSUED_BY',
  'generated by scripts/dena/generate-recovery-backup-codes.sh'
);

INSERT INTO dena.recovery_event (
  realm, username, event_type, operator_username, details
) VALUES (
  '$REALM',
  '$USERNAME',
  'backup_codes_issued',
  '$ISSUED_BY',
  jsonb_build_object('count', $COUNT, 'code_hint', '$code_hint')
);
SQL
  done
  echo "COMMIT;"
} >"$tmp_sql"

kubectl exec -i -n datalake postgresql-datalake-0 -- \
  env PGPASSWORD="$pg_password" \
  psql -v ON_ERROR_STOP=1 -U postgres -d datalake <"$tmp_sql"

chmod 600 "$codes_file"

echo "Codigos de respaldo generados para $REALM/$USERNAME."
echo "Archivo local: $codes_file"
echo "Registro de auditoria guardado en dena.recovery_event."
