image:
  repository: apache/apisix
  tag: 3.16.0-ubuntu
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  http:
    enabled: true
    servicePort: 80
    containerPort: 9080
    nodePort: 30080
  tls:
    servicePort: 443

apisix:
  admin:
    enabled: true
    enable_admin_ui: true
    type: ClusterIP
    credentials:
      admin: edd1c9f034335f136f87ad84b625c8f1
      viewer: 4054f7cf07e344346cd3f287985e76a2
    allow:
      ipList:
        - 127.0.0.1/24
        - 10.0.0.0/8
        - 192.168.0.0/16
  deployment:
    mode: traditional
    role: traditional
    role_traditional:
      config_provider: etcd

etcd:
  enabled: true
  replicaCount: 1
  image:
    registry: docker.io
    repository: bitnamilegacy/etcd
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 4Gi
  auth:
    rbac:
      create: false

ingress-controller:
  enabled: false

