alertmanager:
  enabled: false

defaultRules:
  create: false

grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  service:
    type: NodePort
    nodePort: 31803
    port: 80
    targetPort: 3000
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 192Mi
  sidecar:
    dashboards:
      provider:
        allowUiUpdates: true
    datasources:
      exemplarTraceIdDestinations:
        datasourceUid: tempo
        traceIdLabelName: trace_id
        urlDisplayLabel: View trace
      alertmanager:
        enabled: false
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      isDefault: false
      jsonData:
        maxLines: 1000
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3200
      isDefault: false
      jsonData:
        serviceMap:
          datasourceUid: prometheus
        tracesToLogsV2:
          datasourceUid: loki
          spanStartTimeShift: "-15m"
          spanEndTimeShift: "15m"
          tags:
            - key: service.name
              value: service.name
            - key: k8s.namespace.name
              value: k8s.namespace.name
            - key: k8s.pod.name
              value: k8s.pod.name
          filterByTraceID: false
          filterBySpanID: false
          customQuery: false
        nodeGraph:
          enabled: true

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: ""
    storageSpec: {}
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1024Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      memory: 64Mi
