image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 17.1.0-debian-12-r0
  pullPolicy: IfNotPresent

architecture: standalone

auth:
  enablePostgresUser: true
  username: keycloak
  database: keycloak
  existingSecret: postgresql-auth
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password
    replicationPasswordKey: replication-password

primary:
  persistence:
    enabled: true
    size: 4Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

readReplicas:
  replicaCount: 0

metrics:
  enabled: false

