tempo:
  reportingEnabled: false
  memBallastSizeMbs: 0
  retention: 24h
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 192Mi
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

serviceMonitor:
  enabled: true

persistence:
  enabled: false
